use HTTP 1.1 for Nginx reverse proxy
Otherwise we were getting:
POST /api/v0/query returned 500
play.core.server.common.ServerResultException: HTTP 1.0 client does not support chunked respo

Signed-off-by: Jakub Sokołowski <jakub@status.im>